export const Querykeys = {
  allFavourite: "allFavourite",
  categoryList: "categoryList",
  experiences: "experiences",
  filterListCity: "filterListCity",
  cityList: "cityList",
  getPackages: "get-packages",
  industryList: "industryList",
  jobApplied: "jobApplied",
  jobDetails: "jobDetails",
  jobFilter: "jobFilter",
  jobTitle: "jobTitle",
  profileDetails: "profileDetails",
  qualification: "qualification",
  salary: "salary",
  allJobsQuery: "allJobsQuery",
  stateList: "stateList",
  allCityList: "allCityList",
  latestJobs: "latestJobs",
  blog:"blog",
  blogDetails:"blogDetails",
  resultType:"resultType",
  educationType:"educationType",
  subjects:"subjects"
};