export const AppRoute = {
  Home: "/",
  Find_Jobs: "/jobs",
  Careers: "/careers",
  Membership: "membership",
  Login: "/login",
  ResumeIndex: "/resume-builder",
  ChooseTemplate:"choose-template",
  ResumeMain:"resume-main",
  Info:"info",
  SignUp: "/signup",
  SignUpAll: "/signup",
  Apply_job: "/apply-job",
  Thank_You: "/thank-you",
  Contact_Us: "/contact-us",
  About_Us: "/about-us",
  Subjects: "/subjects",
  Faqs: "/faq",
  Terms_of_use: "/terms",
  Blog: "/blog",
  Privacy_Policy: "/privacy-policy",
  Refund_Policy: "/refund-policy",
  TermsAndConditions: "/terms-and-conditions",
  Dashboard: "/dashboard",
  User_Dashboard: "user-dashboard",
  Resume: "resume",
  Saved_Job: "saved-job",
  Applied_Job: "applied-job",
  Rejected_Job: "rejected-job",
  Accepted_Job: "accepted-job",
  Account_Setting: "account-setting",
  Forgot_password: "/forgot-password",
  ResumeDesignOne:"resume-one",
  services:"resume-builder",
  resume:"resume-builder",
  ShareProfile:"share-profile",
  Profile:"/dashboard/profile",
  
};
